# =============================================================================
# CHAPTER 4: Real Database with SQLModel and Dependency Injection
# =============================================================================
#
# Everything up to Chapter 3 used a Python dict as a fake database.
# That data was lost every time the server restarted.
#
# This chapter introduces a real SQLite database using SQLModel.
# Data now persists in a file called database.db in your project root.
#
# New concepts in this chapter:
#
#   1. SQLModel table     - a Python class that is both a Pydantic model and a DB table
#   2. Depends()          - FastAPI injects a DB session into every route automatically
#   3. session.exec()     - run SELECT queries
#   4. session.get()      - fetch a single row by primary key
#   5. session.add()      - stage a new row for saving
#   6. session.commit()   - write staged changes to the database
#   7. session.refresh()  - reload the object so auto-generated fields like id appear
#   8. session.delete()   - mark a row for deletion
#
# Read the database setup in: my_fastapi_project/database.py
# =============================================================================

from fastapi import APIRouter, HTTPException, Depends
from sqlmodel import SQLModel, Field, Session, select
from typing import Optional

from my_fastapi_project.database import get_session


router = APIRouter(prefix="/v3/items", tags=["items-v3"])


# =============================================================================
# CONCEPT 1: SQLModel Table Class
# =============================================================================
# This single class does two jobs at once:
#   - Pydantic model -> validates request and response data (like Chapter 2)
#   - Database table -> SQLModel creates a real "item" table in database.db
#
# `table=True` is what tells SQLModel to treat this as a DB table.
# Without it, it is just a regular Pydantic model with no database connection.
#
# Field breakdown:
#   id    -> auto-generated by the DB on insert, so we default it to None
#   name  -> stored as TEXT in the database
#   price -> stored as REAL (float) in the database
class Item(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    price: float


# =============================================================================
# CONCEPT 2: Depends() and session.exec()
# =============================================================================
# FastAPI's Depends() runs a helper function before the route and injects
# its result as an argument. Here we use it to get a live database session.
#
# `session: Session = Depends(get_session)` means:
#   - FastAPI calls get_session() from database.py before this route runs
#   - It yields a Session object and passes it in as `session`
#   - After the route finishes, FastAPI closes the session automatically
#
# You never open or close sessions manually. Depends handles it every request.
#
# session.exec(select(Item)).all()
#   select(Item) -> builds SQL: SELECT * FROM item
#   .exec()      -> runs the query
#   .all()       -> returns all matching rows as a list of Item objects
@router.get("/")
async def get_all_items(session: Session = Depends(get_session)):
    items = session.exec(select(Item)).all()
    return items


# =============================================================================
# CONCEPT 3: session.get() - fetch one row by primary key
# =============================================================================
# session.get(Item, item_id) is the fastest way to look up a single row.
# It translates to: SELECT * FROM item WHERE id = item_id LIMIT 1
#
# Returns the Item object if found, or None if no row matches.
# We check for None and raise HTTPException(404) the same way as Chapter 3.
#
# Syntax fix from your attempt:
#   WRONG: raise HTTPException, status_code=404, detail="..."
#   RIGHT: raise HTTPException(status_code=404, detail="...")
#   raise calls a function, so you need parentheses like any function call.
@router.get("/{item_id}")
async def get_item(item_id: int, session: Session = Depends(get_session)):
    item = session.get(Item, item_id)
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    return item


# =============================================================================
# CONCEPT 4: session.add() + session.commit() + session.refresh()
# =============================================================================
# Three steps to save a new row to the database:
#
#   session.add(item)
#     -> Tells SQLModel "I want to save this". Nothing is written yet.
#
#   session.commit()
#     -> Writes all staged changes to the database file.
#     -> At this point the DB assigns an auto-generated id to the item.
#
#   session.refresh(item)
#     -> The `item` object in Python still has id=None after commit.
#     -> refresh() re-reads the row from the DB and updates the Python object.
#     -> After this line, item.id has the real auto-generated value.
@router.post("/", status_code=201)
async def create_item(item: Item, session: Session = Depends(get_session)):
    session.add(item)
    session.commit()
    session.refresh(item)
    return item


# =============================================================================
# CONCEPT 5: Updating a row - fetch, modify fields, commit
# =============================================================================
# There is no session.update(). The pattern in SQLModel is:
#   1. Fetch the existing row with session.get()
#   2. Modify its fields directly on the Python object
#   3. session.add(item) -> stages the updated object
#   4. session.commit()  -> writes the changes to the database
#   5. session.refresh(item) -> reloads the object with the latest DB state
@router.put("/{item_id}")
async def update_item(item_id: int, updated: Item, session: Session = Depends(get_session)):
    item = session.get(Item, item_id)
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    item.name = updated.name
    item.price = updated.price
    session.add(item)
    session.commit()
    session.refresh(item)
    return item


# =============================================================================
# CONCEPT 6: session.delete() - remove a row from the database
# =============================================================================
# Pattern: fetch first, then delete.
# Always check the item exists before trying to delete.
# session.delete() stages the deletion.
# session.commit() applies it to the database permanently.
@router.delete("/{item_id}")
async def delete_item(item_id: int, session: Session = Depends(get_session)):
    item = session.get(Item, item_id)
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    session.delete(item)
    session.commit()
    return {"message": f"Item '{item.name}' deleted successfully"}
